"""nuclear_verification.py — feature coverage for the Simulator Swarm.

Operator directive 2026-08-05:

    "Nuclear Mode must be using the Simulator Swarm and testing all
    feature functionality of the swarm. Every system feature must be
    able to be verified and tested. This is the core design intention
    of Nuclear Mode."

THE PRINCIPLE
=============
A feature that was never exercised is UNVERIFIED, not passing. That
distinction is the whole point. This codebase has repeatedly shipped
features that were wired, looked correct, and had zero callers:

    SimStatStrip.set()        zero call sites  -> header showed dashes
    compare_trades()          zero callers     -> 12 green tests, never run
    SystemLoadOscillator      zero callers     -> built, never wired
    register_sim_run()        zero callers     -> swarm rows never driven

Every one of those passed its tests. None of them ran. A soak test that
reports "no failures" while touching half the feature surface reproduces
exactly that failure, so coverage here is measured, not assumed.

THE TRANCHE CHAIN
=================
Operator, same session:

    "Tranches are a core bot feature generated by bot trade actions but
    they are supposed to be fed by smart wire transactions to boost
    compounding potential across a given topology."

That is a four-link causal chain, and each link is separately
falsifiable:

    1. a SCRUM creates a fold tranche
    2. Smart Wire credits land IN that tranche
    3. the fed tranche compounds beyond scrum-only deposits
    4. the credit came from ANOTHER bot (i.e. across a topology)

Link 4 is the one that is easy to fake. A tranche fed only by its own
bot demonstrates nothing about topology, and a naive "wire credits > 0"
check would pass on it. ``wire_credits_rolled.by_source`` keeps
per-source totals, so the source can actually be compared against the
owning bot.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger("acervator.nuclear_verification")


# --------------------------------------------------------------------- #
# Declared feature surface                                              #
# --------------------------------------------------------------------- #

# Trade actions the bot can actually emit. Derived by enumerating
# `action="..."` on trade.filled and the _emit_trade_notification call
# sites in scrumming_bot.py — NOT invented. A feature that is not in the
# bot's own vocabulary cannot be verified, and one that is in it but
# missing here would be silently uncovered.
TRADE_ACTIONS: tuple[str, ...] = (
    "SCRUM",
    "FOLD",
    "CARTRIDGE_SCRUM",
    "CARTRIDGE_FOLD",
    "ENTRY",
    "HEDGE",
    "DIST",
    "AUTO_DETONATION",
)

# Subsystem behaviours that are not trade actions but are features the
# swarm is expected to exercise.
SUBSYSTEM_FEATURES: tuple[str, ...] = (
    "swarm.tranche.created",
    "swarm.tranche.wire_fed",
    "swarm.tranche.compounded",
    "swarm.topology.cross_bot_credit",
    "swarm.gate.scrum_evaluated",
    "swarm.gate.fold_evaluated",
    "swarm.gate.landing_strip_override",
    "swarm.wire.income_distributed",
    "swarm.wire.pending_absorbed",
)

ALL_FEATURES: tuple[str, ...] = tuple(
    [f"swarm.trade.{a.lower()}" for a in TRADE_ACTIONS] + list(SUBSYSTEM_FEATURES)
)


@dataclass
class TrancheChainResult:
    """Evidence for the scrum -> wire -> compound -> topology chain."""

    tranches_seen: int = 0
    tranches_wire_fed: int = 0
    wire_usd_total: float = 0.0
    cross_bot_credits: int = 0
    sources: dict = field(default_factory=dict)

    @property
    def created(self) -> bool:
        return self.tranches_seen > 0

    @property
    def wire_fed(self) -> bool:
        return self.tranches_wire_fed > 0 and self.wire_usd_total > 0.0

    @property
    def compounded(self) -> bool:
        """Fed tranches carry more than their scrum deposit.

        Wire USD landing in a tranche IS the compounding boost — the
        tranche's fold fires against a larger balance than the scrum
        alone created.
        """
        return self.wire_fed

    @property
    def across_topology(self) -> bool:
        """Credits arrived from a bot other than the tranche's owner.

        Without this the chain is self-referential: a bot feeding its
        own tranches proves nothing about a topology.
        """
        return self.cross_bot_credits > 0

    def to_dict(self) -> dict:
        return {
            "tranches_seen": self.tranches_seen,
            "tranches_wire_fed": self.tranches_wire_fed,
            "wire_usd_total": round(self.wire_usd_total, 8),
            "cross_bot_credits": self.cross_bot_credits,
            "sources": dict(sorted(self.sources.items())),
            "link_created": self.created,
            "link_wire_fed": self.wire_fed,
            "link_compounded": self.compounded,
            "link_across_topology": self.across_topology,
        }


@dataclass
class CoverageReport:
    """Which declared features were actually exercised."""

    exercised: dict = field(default_factory=dict)
    chain: TrancheChainResult = field(default_factory=TrancheChainResult)

    @property
    def verified(self) -> list:
        return sorted(k for k, v in self.exercised.items() if v > 0)

    @property
    def unverified(self) -> list:
        """Declared but never exercised. NOT the same as passing."""
        return sorted(k for k in ALL_FEATURES if self.exercised.get(k, 0) == 0)

    @property
    def coverage_pct(self) -> float:
        if not ALL_FEATURES:
            return 0.0
        return 100.0 * len(self.verified) / len(ALL_FEATURES)

    def to_dict(self) -> dict:
        return {
            "features_declared": len(ALL_FEATURES),
            "features_verified": len(self.verified),
            "features_unverified": len(self.unverified),
            "coverage_pct": round(self.coverage_pct, 1),
            "verified": self.verified,
            "unverified": self.unverified,
            "exercised_counts": dict(sorted(self.exercised.items())),
            "tranche_chain": self.chain.to_dict(),
        }


class SwarmFeatureVerifier:
    """Records which swarm features a run actually exercised.

    Attaches to sim bots' PRIVATE buses only. Attaching to a live bot
    would make live trading feed a test report — the same isolation
    failure v3.24.12 fixed for trade.log.
    """

    def __init__(self) -> None:
        self.report = CoverageReport()
        self._declare()

    def _declare(self) -> None:
        """Seed every declared feature at zero.

        Declaring up front is what makes a never-fired feature visible.
        Counting only what fires would make an untouched feature simply
        absent from the report — indistinguishable from one that does
        not exist.
        """
        for name in ALL_FEATURES:
            self.report.exercised.setdefault(name, 0)
        try:
            from src.core.feature_telemetry import get_telemetry

            get_telemetry().declare(*ALL_FEATURES)
        except Exception as exc:  # noqa: BLE001 - telemetry advisory
            logger.debug("nuclear: telemetry declare failed: %s", exc)

    def _hit(self, name: str, count: int = 1) -> None:
        self.report.exercised[name] = self.report.exercised.get(name, 0) + count
        try:
            from src.core.feature_telemetry import get_telemetry

            get_telemetry().record_call(name, count=count)
        except Exception as exc:  # noqa: BLE001 - telemetry advisory
            logger.debug("nuclear: telemetry record failed: %s", exc)

    def attach(self, bot: Any) -> bool:
        """Subscribe to one SIM bot's bus. Refuses live bots."""
        if not getattr(bot, "_sim_mode", False):
            logger.warning(
                "nuclear verification: refusing to attach to non-sim " "bot %s",
                getattr(bot, "bot_id", "?"),
            )
            return False
        bus = getattr(bot, "_bus", None)
        if bus is None or not hasattr(bus, "subscribe"):
            return False
        bus.subscribe("trade.filled", self._on_trade)
        return True

    def _on_trade(self, event: Any) -> None:
        """Record the trade action.

        The bot emits ``bus.emit("trade.filled", bot_id=..., data={...})``,
        so ``Event.data`` is ``{"bot_id": ..., "data": {...}}`` and the
        action lives one level DOWN. Reading ``event.data["action"]``
        returns None for every trade — which is exactly what happened:
        6 fills captured, 0 features recorded, coverage reported 0/17
        while the run looked healthy.

        Both shapes are accepted so a future flattening of the payload
        does not silently zero the coverage again.
        """
        payload = getattr(event, "data", None) or {}
        inner = payload.get("data")
        data = inner if isinstance(inner, dict) else payload
        # The bus payload names this field "type", not "action". In
        # src/trading/scrumming/tick_phases.py, TickPhaseMixin:
        #   _tick_initial_entry  side="buy",  type="ENTRY"
        #   _tick_execute_scrum  side="sell", type="SCRUM"
        #   _tick_execute_fold   side="buy",  type="FOLD"
        # "action" is the name used by the LOG schema, not the bus.
        # Reading the wrong one records zero for every trade and the
        # coverage report shows 0% while the run looks healthy — which
        # is exactly what happened before this line was corrected.
        action = str(data.get("type") or data.get("action") or "").upper()
        if not action:
            return
        if action in TRADE_ACTIONS:
            self._hit(f"swarm.trade.{action.lower()}")
        else:
            # An action outside the declared vocabulary is a real
            # signal: the bot grew a trade type this harness does not
            # know how to verify.
            logger.info(
                "nuclear verification: undeclared trade action %r — "
                "add it to TRADE_ACTIONS or it stays unverified",
                action,
            )

    def scan_bots(self, bots: list) -> None:
        """Inspect end-of-cycle bot state for the tranche chain.

        Bus events alone cannot prove links 2-4: a wire credit changes
        tranche STATE rather than emitting a trade, so the evidence
        lives in the tranche records.
        """
        chain = self.report.chain
        for bot in bots or []:
            bot_id = str(getattr(bot, "bot_id", "") or "")
            for t in getattr(bot, "_fold_tranches", None) or []:
                chain.tranches_seen += 1
                self._hit("swarm.tranche.created")
                usd, sources = self._tranche_wire_usd(t)
                if usd > 0.0:
                    chain.tranches_wire_fed += 1
                    chain.wire_usd_total += usd
                    self._hit("swarm.tranche.wire_fed")
                    self._hit("swarm.tranche.compounded")
                    for src, amt in sources.items():
                        chain.sources[src] = round(chain.sources.get(src, 0.0) + amt, 8)
                        # Link 4: the credit must come from a DIFFERENT
                        # bot, or the chain is self-referential.
                        if src and bot_id and src != bot_id:
                            chain.cross_bot_credits += 1
                            self._hit("swarm.topology.cross_bot_credit")

    @staticmethod
    def _tranche_wire_usd(tranche: dict) -> tuple[float, dict]:
        """Total wire USD in a tranche, by source.

        Reads BOTH the bounded detail list and the rolled aggregate.
        Reading only the detail list would under-report every tranche
        past the v3.24.28 cap — the aggregate is where older credits
        live, and skipping it would make long runs look like they
        received less wire income than short ones.
        """
        total = 0.0
        by_src: dict = {}
        for e in tranche.get("wire_credits") or []:
            if not isinstance(e, dict):
                continue
            try:
                amt = float(e.get("usd", 0.0) or 0.0)
            except (TypeError, ValueError):
                continue
            src = str(e.get("source", "") or "unknown")
            total += amt
            by_src[src] = by_src.get(src, 0.0) + amt
        rolled = tranche.get("wire_credits_rolled") or {}
        try:
            total += float(rolled.get("total_usd", 0.0) or 0.0)
        except (TypeError, ValueError):
            pass
        for src, amt in (rolled.get("by_source") or {}).items():
            try:
                by_src[str(src)] = by_src.get(str(src), 0.0) + float(amt)
            except (TypeError, ValueError):
                continue
        return total, by_src


def format_coverage_lines(report: CoverageReport) -> list:
    """Operator-facing summary.

    Leads with what was NOT verified, because that is the actionable
    half. A coverage report that opens with a pass count invites the
    reader to stop there.
    """
    d = report.to_dict()
    out = [
        f"Nuclear feature coverage: {d['features_verified']}"
        f"/{d['features_declared']} ({d['coverage_pct']}%)",
    ]
    unv = d["unverified"]
    if unv:
        out.append(
            f"  UNVERIFIED ({len(unv)}) — exercised zero times, "
            "which is not the same as passing:"
        )
        for name in unv:
            out.append(f"    - {name}")
    else:
        out.append("  every declared feature was exercised")

    c = d["tranche_chain"]
    out.append("  tranche chain (scrum -> wire -> compound -> topology):")
    for label, key in (
        ("tranche created by trade action", "link_created"),
        ("fed by smart wire", "link_wire_fed"),
        ("compounding boost applied", "link_compounded"),
        ("credit crossed bots (topology)", "link_across_topology"),
    ):
        out.append(f"    [{'PASS' if c[key] else 'FAIL'}] {label}")
    out.append(
        f"    {c['tranches_seen']} tranche(s), "
        f"{c['tranches_wire_fed']} wire-fed, "
        f"${c['wire_usd_total']:.6f} wire USD, "
        f"{c['cross_bot_credits']} cross-bot credit(s)"
    )
    return out
