// SPDX-License-Identifier: Apache-2.0
// ACERVATOR TROPHY — ERC-721 NFT
// Chain: Base (Coinbase L2)
// =============================================================================
// Soulbound-optional ERC-721 trophy NFTs awarded alongside ACRV tokens.
// Metadata and artwork are fully on-chain — no IPFS dependency.
//
// Each NFT encodes:
//   • Rarity tier (Harvest / Gold Fold / Bear Slayer / Grand Accumulator / Ekthelius)
//   • Season number
//   • Competition ID
//   • Bot's advantage % at win time
//   • Rank within the competition field
//   • Market regime (BULL / BEAR / SIDEWAYS)
//   • Merkle root of the winning trade log (provable legitimacy)
//
// The SVG artwork is stored tier-by-tier as base64 constants set at deployment.
// Each trophy of the same tier is visually identical; metadata differentiates them.
//
// Supply is bounded by the underlying competition caps:
//   Ekthelius        — max 21 ever (enforced in CompetitionRegistry)
//   Grand Accumulator — max 1,000 ever
//   Others           — season-budget bounded
// =============================================================================
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Strings.sol";
import "@openzeppelin/contracts/utils/Base64.sol";

contract AcervatorTrophy is ERC721, Ownable {
    using Strings for uint256;

    // ── State ─────────────────────────────────────────────────────────────────

    uint256 private _nextTokenId = 1;

    /// Only CompetitionRegistry may mint trophies.
    address public immutable registry;

    // ── Trophy metadata per token ─────────────────────────────────────────────

    struct TrophyMetadata {
        string  tier;            // "Harvest" | "Gold Fold" | "Bear Slayer" | ...
        string  tierEmoji;       // "🌾" | "🪙" | "🐻" | "⚡" | "∞"
        uint256 season;
        string  competitionId;
        uint256 rank;
        uint256 fieldSize;
        int256  advantageBps;    // e.g. 2950 = +29.50%
        string  marketRegime;    // "BULL" | "BEAR" | "SIDEWAYS" | "ANY"
        bytes32 merkleRoot;      // winning trade log commitment
        address botWallet;
        uint256 mintedAt;
    }

    mapping(uint256 => TrophyMetadata) public trophyData;

    // ── Tier SVG art (base64-encoded, set at deployment) ──────────────────────
    // Each value is the base64-encoded SVG for that tier.
    // Generated by trophy_generator.py and injected at deploy time.

    mapping(string => string) private _tierSvgB64;

    // ── Tier colors (for on-chain metadata) ───────────────────────────────────

    mapping(string => string) private _tierColor;

    // ── Events ────────────────────────────────────────────────────────────────

    event TrophyMinted(
        uint256 indexed tokenId,
        address indexed recipient,
        string  tier,
        uint256 season,
        string  competitionId,
        int256  advantageBps
    );

    event SvgUpdated(string tier);

    // ── Constructor ───────────────────────────────────────────────────────────

    constructor(address _registry)
        ERC721("Acervator Trophy", "ACTROPH")
        Ownable(msg.sender)
    {
        require(_registry != address(0), "Trophy: registry cannot be zero");
        registry = _registry;

        // Tier colors (hex, for JSON attributes)
        _tierColor["Harvest"]           = "#FFCC44";
        _tierColor["Gold Fold"]         = "#FFD700";
        _tierColor["Bear Slayer"]       = "#FF3344";
        _tierColor["Grand Accumulator"] = "#00FFEE";
        _tierColor["Ekthelius"]         = "#FF00AA";
    }

    // ── Modifiers ─────────────────────────────────────────────────────────────

    modifier onlyRegistry() {
        require(msg.sender == registry || msg.sender == owner(),
                "Trophy: caller is not registry or owner");
        _;
    }

    // ── SVG management ────────────────────────────────────────────────────────

    /**
     * @notice Upload the base64-encoded SVG for a tier.
     * @dev    Called during deployment (or upgrade) by the owner.
     *         Each SVG is ~10–15KB base64 — gas cost is one-time at upload.
     */
    function setTierSvg(string calldata tier, string calldata svgBase64)
        external onlyOwner
    {
        _tierSvgB64[tier] = svgBase64;
        emit SvgUpdated(tier);
    }

    function getTierSvg(string calldata tier)
        external view returns (string memory)
    {
        return _tierSvgB64[tier];
    }

    // ── Minting ───────────────────────────────────────────────────────────────

    /**
     * @notice Mint a trophy NFT to the winning bot's wallet.
     * @dev    Called by CompetitionRegistry immediately after token award.
     */
    function mint(
        address         recipient,
        string calldata tier,
        string calldata tierEmoji,
        uint256         season,
        string calldata competitionId,
        uint256         rank,
        uint256         fieldSize,
        int256          advantageBps,
        string calldata marketRegime,
        bytes32         merkleRoot
    ) external onlyRegistry returns (uint256 tokenId) {
        require(recipient != address(0), "Trophy: mint to zero address");
        require(bytes(tier).length > 0,  "Trophy: empty tier");
        require(bytes(_tierSvgB64[tier]).length > 0,
                "Trophy: SVG not uploaded for this tier");

        tokenId = _nextTokenId++;
        _safeMint(recipient, tokenId);

        trophyData[tokenId] = TrophyMetadata({
            tier:          tier,
            tierEmoji:     tierEmoji,
            season:        season,
            competitionId: competitionId,
            rank:          rank,
            fieldSize:     fieldSize,
            advantageBps:  advantageBps,
            marketRegime:  marketRegime,
            merkleRoot:    merkleRoot,
            botWallet:     recipient,
            mintedAt:      block.timestamp
        });

        emit TrophyMinted(tokenId, recipient, tier, season,
                          competitionId, advantageBps);
    }

    // ── tokenURI — fully on-chain ─────────────────────────────────────────────

    /**
     * @notice Returns the full ERC-721 metadata as a base64-encoded data URI.
     *         No external URLs. Art and metadata fully on-chain.
     */
    function tokenURI(uint256 tokenId)
        public view override returns (string memory)
    {
        _requireOwned(tokenId);
        TrophyMetadata memory m = trophyData[tokenId];
        string memory svgB64   = _tierSvgB64[m.tier];

        // Build the JSON attributes array
        string memory attrs = string.concat(
            '[',
            _attr("Tier",           m.tier),          ',',
            _attr("Emoji",          m.tierEmoji),      ',',
            _attrNum("Season",      m.season),         ',',
            _attr("Competition",    m.competitionId),  ',',
            _attrNum("Rank",        m.rank),           ',',
            _attrNum("Field Size",  m.fieldSize),      ',',
            _attrSigned("Advantage (bps)", m.advantageBps), ',',
            _attr("Market Regime",  m.marketRegime),   ',',
            _attr("Tier Color",     _tierColor[m.tier]),
            ']'
        );

        // Advantage in human-readable form (e.g. "+29.50%")
        string memory advStr = _formatBps(m.advantageBps);

        string memory json = string.concat(
            '{"name":"',
            m.tierEmoji, unicode' Acervator Trophy — ', m.tier,
            ' #', tokenId.toString(),
            '","description":"',
            'A Proof-of-Accumulation trophy awarded to the bot ranked #',
            m.rank.toString(),
            ' in Competition ', m.competitionId,
            ' (Season ', m.season.toString(), '). ',
            'Advantage: ', advStr, '. ',
            'Market: ', m.marketRegime, '. ',
            'Merkle root: 0x', _bytes32ToHex(m.merkleRoot),
            '","image":"data:image/svg+xml;base64,', svgB64,
            '","attributes":', attrs,
            '}'
        );

        return string.concat(
            "data:application/json;base64,",
            Base64.encode(bytes(json))
        );
    }

    // ── Views ─────────────────────────────────────────────────────────────────

    function totalMinted() external view returns (uint256) {
        return _nextTokenId - 1;
    }

    function tokensOfOwner(address owner_, uint256 maxResults)
        external view returns (uint256[] memory)
    {
        uint256 total  = _nextTokenId - 1;
        uint256 count  = 0;
        uint256[] memory tmp = new uint256[](maxResults);
        for (uint256 i = 1; i <= total && count < maxResults; i++) {
            if (_ownerOf(i) == owner_) {
                tmp[count++] = i;
            }
        }
        uint256[] memory result = new uint256[](count);
        for (uint256 j = 0; j < count; j++) result[j] = tmp[j];
        return result;
    }

    function getTrophyTier(uint256 tokenId) external view returns (string memory) {
        return trophyData[tokenId].tier;
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    function _attr(string memory key, string memory value)
        internal pure returns (string memory)
    {
        return string.concat(
            '{"trait_type":"', key, '","value":"', value, '"}');
    }

    function _attrNum(string memory key, uint256 value)
        internal pure returns (string memory)
    {
        return string.concat(
            '{"trait_type":"', key, '","value":', value.toString(), '}');
    }

    function _attrSigned(string memory key, int256 value)
        internal pure returns (string memory)
    {
        string memory v = value >= 0
            ? uint256(value).toString()
            : string.concat("-", uint256(-value).toString());
        return string.concat('{"trait_type":"', key, '","value":', v, '}');
    }

    function _formatBps(int256 bps) internal pure returns (string memory) {
        // Convert basis points to percentage string: 2950 → "+29.50%"
        string memory sign   = bps >= 0 ? "+" : "-";
        uint256 absBps       = bps >= 0 ? uint256(bps) : uint256(-bps);
        uint256 whole        = absBps / 100;
        uint256 frac         = absBps % 100;
        string memory fracStr = frac < 10
            ? string.concat("0", frac.toString())
            : frac.toString();
        return string.concat(sign, whole.toString(), ".", fracStr, "%");
    }

    function _bytes32ToHex(bytes32 b) internal pure returns (string memory) {
        bytes memory hexChars = "0123456789abcdef";
        bytes memory str = new bytes(64);
        for (uint256 i = 0; i < 32; i++) {
            str[i*2]   = hexChars[uint8(b[i]) >> 4];
            str[i*2+1] = hexChars[uint8(b[i]) & 0x0f];
        }
        return string(str);
    }
}
