// SPDX-License-Identifier: Apache-2.0
// ACERVATOR TROPHY — ERC-721 NFT
// Chain: Base (Coinbase L2)
// =============================================================================
// ERC-721 trophy NFTs awarded alongside ACRV tokens. Freely transferable: this
// contract declares no transfer hook, no override and no soulbound flag.
// Metadata and artwork are fully on-chain — no IPFS dependency.
//
// Each NFT encodes:
//   • Rarity tier (Harvest / Gold Fold / Bear Slayer / Grand Accumulator / Ekthelius)
//   • Season number
//   • Competition ID
//   • Bot's advantage % at win time
//   • Rank within the competition field
//   • Market regime (BULL / BEAR / SIDEWAYS)
//   • Merkle root of the winning trade log (provable legitimacy)
//
// The SVG artwork is stored tier-by-tier as base64 constants set at deployment.
// Each trophy of the same tier is visually identical; metadata differentiates them.
//
// Four tiers carry a lifetime ceiling, enforced inside mint against a counter
// this contract keeps per tier name. Harvest is the only uncapped tier, and a
// tier name outside the five is refused, so no name reaches an uncounted slot.
// mint admits registry alone. CompetitionRegistry still holds no reference to
// this contract, so mint has no caller until that reference lands: its
// MAX_EKTHELIUS and MAX_GRAND_ACCUMULATOR bound ACRV awards, and the constants
// below bound these NFTs.
// =============================================================================
pragma solidity 0.8.36;

import {ERC721} from "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {Ownable2Step} from "@openzeppelin/contracts/access/Ownable2Step.sol";
import {Strings} from "@openzeppelin/contracts/utils/Strings.sol";
import {Base64} from "@openzeppelin/contracts/utils/Base64.sol";
import {SafeCast} from "@openzeppelin/contracts/utils/math/SafeCast.sol";
import {SignedMath} from "@openzeppelin/contracts/utils/math/SignedMath.sol";

contract AcervatorTrophy is ERC721, Ownable2Step {
    using Strings for uint256;

    // ── State ─────────────────────────────────────────────────────────────────

    uint256 private _nextTokenId = 1;

    /// Only CompetitionRegistry may mint trophies.
    address public immutable registry;

    // ── Tier lifetime supply caps (enforced in mint, immutable) ───────────────
    // Harvest has no constant and no ceiling. These four match the max_ever
    // values in src/competition/season_schedule.py RARITY_TIERS.

    uint256 public constant MAX_GOLD_FOLD         = 100_000;
    uint256 public constant MAX_BEAR_SLAYER       = 10_000;
    uint256 public constant MAX_GRAND_ACCUMULATOR = 1_000;
    uint256 public constant MAX_EKTHELIUS         = 21;

    mapping(string => uint256) public tierMinted;

    // ── Trophy metadata per token ─────────────────────────────────────────────

    struct TrophyMetadata {
        string  tier;            // "Harvest" | "Gold Fold" | "Bear Slayer" | ...
        string  tierEmoji;       // "🌾" | "🪙" | "🐻" | "⚡" | "∞"
        uint256 season;
        string  competitionId;
        uint256 rank;
        uint256 fieldSize;
        int256  advantageBps;    // e.g. 2950 = +29.50%
        string  marketRegime;    // "BULL" | "BEAR" | "SIDEWAYS" | "ANY"
        bytes32 merkleRoot;      // winning trade log commitment
        address botWallet;
        uint256 mintedAt;
    }

    mapping(uint256 => TrophyMetadata) public trophyData;

    // ── Tier SVG art (base64-encoded, set at deployment) ──────────────────────
    // Each value is the base64-encoded SVG for that tier.
    // Generated by trophy_generator.py and injected at deploy time.

    mapping(string => string) private _tierSvgB64;

    // ── Tier colors (for on-chain metadata) ───────────────────────────────────

    mapping(string => string) private _tierColor;

    // ── Errors ────────────────────────────────────────────────────────────────

    error OwnershipCannotBeRenounced();

    // ── Events ────────────────────────────────────────────────────────────────

    event TrophyMinted(
        uint256 indexed tokenId,
        address indexed recipient,
        string  tier,
        uint256 season,
        string  competitionId,
        int256  advantageBps
    );

    event SvgUpdated(string tier);

    // ── Constructor ───────────────────────────────────────────────────────────

    constructor(address _registry)
        ERC721("Acervator Trophy", "ACTROPH")
        Ownable(msg.sender)
    {
        require(_registry != address(0), "Trophy: registry cannot be zero");
        require(_registry.code.length > 0, "Trophy: registry not a contract");
        registry = _registry;

        // Tier colors (hex, for JSON attributes)
        _tierColor["Harvest"]           = "#FFCC44";
        _tierColor["Gold Fold"]         = "#FFD700";
        _tierColor["Bear Slayer"]       = "#FF3344";
        _tierColor["Grand Accumulator"] = "#00FFEE";
        _tierColor["Ekthelius"]         = "#FF00AA";
    }

    // ── Modifiers ─────────────────────────────────────────────────────────────

    modifier onlyRegistry() {
        require(msg.sender == registry, "Trophy: caller is not registry");
        _;
    }

    // ── SVG management ────────────────────────────────────────────────────────

    /**
     * @notice Upload the base64-encoded SVG for a tier.
     * @dev    Called during deployment (or upgrade) by the owner.
     *         Each SVG is ~10–15KB base64 — gas cost is one-time at upload.
     */
    function setTierSvg(string calldata tier, string calldata svgBase64)
        external onlyOwner
    {
        _tierSvgB64[tier] = svgBase64;
        emit SvgUpdated(tier);
    }

    function getTierSvg(string calldata tier)
        external view returns (string memory)
    {
        return _tierSvgB64[tier];
    }

    // ── Ownership cannot be abandoned ─────────────────────────────────────────

    /// @notice Refuse to abandon ownership, because setTierSvg is owner-only and
    ///         mint reverts on a tier holding no SVG.
    function renounceOwnership() public pure override {
        revert OwnershipCannotBeRenounced();
    }

    // ── Minting ───────────────────────────────────────────────────────────────

    /**
     * @notice Mint a trophy NFT to the winning bot's wallet.
     * @dev    Called by CompetitionRegistry immediately after token award.
     *
     *         _safeMint is the last statement. The tier count, the metadata and
     *         the event all land first, so a recipient re-entering through
     *         onERC721Received reads a finished token.
     */
    function mint(
        address         recipient,
        string calldata tier,
        string calldata tierEmoji,
        uint256         season,
        string calldata competitionId,
        uint256         rank,
        uint256         fieldSize,
        int256          advantageBps,
        string calldata marketRegime,
        bytes32         merkleRoot
    ) external onlyRegistry returns (uint256 tokenId) {
        require(recipient != address(0), "Trophy: mint to zero address");
        require(bytes(tier).length > 0,  "Trophy: empty tier");
        require(bytes(_tierSvgB64[tier]).length > 0,
                "Trophy: SVG not uploaded for this tier");

        _countTierMint(tier);

        tokenId = _nextTokenId++;

        trophyData[tokenId] = TrophyMetadata({
            tier:          tier,
            tierEmoji:     tierEmoji,
            season:        season,
            competitionId: competitionId,
            rank:          rank,
            fieldSize:     fieldSize,
            advantageBps:  advantageBps,
            marketRegime:  marketRegime,
            merkleRoot:    merkleRoot,
            botWallet:     recipient,
            mintedAt:      block.timestamp
        });

        emit TrophyMinted(tokenId, recipient, tier, season,
                          competitionId, advantageBps);

        _safeMint(recipient, tokenId);
    }

    // ── tokenURI — fully on-chain ─────────────────────────────────────────────

    /**
     * @notice Returns the full ERC-721 metadata as a base64-encoded data URI.
     *         No external URLs. Art and metadata fully on-chain.
     */
    function tokenURI(uint256 tokenId)
        public view override returns (string memory)
    {
        _requireOwned(tokenId);
        TrophyMetadata memory m = trophyData[tokenId];
        string memory svgB64   = _tierSvgB64[m.tier];

        // Build the JSON attributes array
        string memory attrs = string.concat(
            "[",
            _attr("Tier",           m.tier),          ",",
            _attr("Emoji",          m.tierEmoji),      ",",
            _attrNum("Season",      m.season),         ",",
            _attr("Competition",    m.competitionId),  ",",
            _attrNum("Rank",        m.rank),           ",",
            _attrNum("Field Size",  m.fieldSize),      ",",
            _attrSigned("Advantage (bps)", m.advantageBps), ",",
            _attr("Market Regime",  m.marketRegime),   ",",
            _attr("Tier Color",     _tierColor[m.tier]),
            "]"
        );

        // Advantage in human-readable form (e.g. "+29.50%")
        string memory advStr = _formatBps(m.advantageBps);

        string memory json = string.concat(
            "{\"name\":\"",
            m.tierEmoji, unicode" Acervator Trophy — ", m.tier,
            " #", tokenId.toString(),
            "\",\"description\":\"",
            "A Proof-of-Accumulation trophy awarded to the bot ranked #",
            m.rank.toString(),
            " in Competition ", m.competitionId,
            " (Season ", m.season.toString(), "). ",
            "Advantage: ", advStr, ". ",
            "Market: ", m.marketRegime, ". ",
            "Merkle root: 0x", _bytes32ToHex(m.merkleRoot),
            "\",\"image\":\"data:image/svg+xml;base64,", svgB64,
            "\",\"attributes\":", attrs,
            "}"
        );

        return string.concat(
            "data:application/json;base64,",
            Base64.encode(bytes(json))
        );
    }

    // ── Views ─────────────────────────────────────────────────────────────────

    function totalMinted() external view returns (uint256) {
        return _nextTokenId - 1;
    }

    function tokensOfOwner(address owner_, uint256 maxResults)
        external view returns (uint256[] memory)
    {
        uint256 total  = _nextTokenId - 1;
        uint256 count  = 0;
        uint256[] memory tmp = new uint256[](maxResults);
        for (uint256 i = 1; i <= total && count < maxResults; i++) {
            if (_ownerOf(i) == owner_) {
                tmp[count++] = i;
            }
        }
        uint256[] memory result = new uint256[](count);
        for (uint256 j = 0; j < count; j++) result[j] = tmp[j];
        return result;
    }

    function getTrophyTier(uint256 tokenId) external view returns (string memory) {
        return trophyData[tokenId].tier;
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /// @dev Refuses a tier outside the five and a mint at a capped tier's
    ///      ceiling, then raises that tier's counter.
    function _countTierMint(string calldata tier) private {
        bytes32 tierHash = keccak256(bytes(tier));
        if (tierHash == keccak256("Ekthelius")) {
            require(tierMinted[tier] < MAX_EKTHELIUS,
                    "Trophy: Ekthelius supply of 21 exhausted");
        } else if (tierHash == keccak256("Grand Accumulator")) {
            require(tierMinted[tier] < MAX_GRAND_ACCUMULATOR,
                    "Trophy: Grand Accumulator supply of 1,000 exhausted");
        } else if (tierHash == keccak256("Bear Slayer")) {
            require(tierMinted[tier] < MAX_BEAR_SLAYER,
                    "Trophy: Bear Slayer supply of 10,000 exhausted");
        } else if (tierHash == keccak256("Gold Fold")) {
            require(tierMinted[tier] < MAX_GOLD_FOLD,
                    "Trophy: Gold Fold supply of 100,000 exhausted");
        } else {
            require(tierHash == keccak256("Harvest"), "Trophy: unknown tier");
        }
        ++tierMinted[tier];
    }

    function _attr(string memory key, string memory value)
        internal pure returns (string memory)
    {
        return string.concat(
            "{\"trait_type\":\"", key, "\",\"value\":\"", value, "\"}");
    }

    function _attrNum(string memory key, uint256 value)
        internal pure returns (string memory)
    {
        return string.concat(
            "{\"trait_type\":\"", key, "\",\"value\":", value.toString(), "}");
    }

    function _attrSigned(string memory key, int256 value)
        internal pure returns (string memory)
    {
        string memory v = value >= 0
            ? SafeCast.toUint256(value).toString()
            : string.concat("-", SignedMath.abs(value).toString());
        return string.concat("{\"trait_type\":\"", key, "\",\"value\":", v, "}");
    }

    /// @dev SignedMath.abs carries the full int256 range, so the most negative
    ///      basis-point value formats instead of reverting inside tokenURI.
    function _formatBps(int256 bps) internal pure returns (string memory) {
        // Convert basis points to percentage string: 2950 → "+29.50%"
        string memory sign   = bps >= 0 ? "+" : "-";
        uint256 absBps       = SignedMath.abs(bps);
        uint256 whole        = absBps / 100;
        uint256 frac         = absBps % 100;
        string memory fracStr = frac < 10
            ? string.concat("0", frac.toString())
            : frac.toString();
        return string.concat(sign, whole.toString(), ".", fracStr, "%");
    }

    function _bytes32ToHex(bytes32 b) internal pure returns (string memory) {
        bytes memory hexChars = "0123456789abcdef";
        bytes memory str = new bytes(64);
        for (uint256 i = 0; i < 32; i++) {
            str[i*2]   = hexChars[uint8(b[i]) >> 4];
            str[i*2+1] = hexChars[uint8(b[i]) & 0x0f];
        }
        return string(str);
    }
}
