// SPDX-License-Identifier: Apache-2.0
// ACERVATOR TROPHY — ERC-721 NFT
// Chain: Base (Coinbase L2)
// =============================================================================
// ERC-721 trophy NFTs awarded alongside ACRV tokens. Freely transferable: this
// contract declares no transfer hook, no override and no soulbound flag.
// Metadata and artwork are fully on-chain — no IPFS dependency.
//
// Each NFT encodes:
//   • Rarity tier (Harvest / Gold Fold / Bear Slayer / Grand Accumulator / Ekthelius)
//   • Season number
//   • Competition ID
//   • Bot's advantage % at win time
//   • Rank within the competition field
//   • Market regime (BULL / BEAR / SIDEWAYS)
//   • Merkle root of the winning trade log (provable legitimacy)
//
// The SVG artwork is stored tier-by-tier as base64 constants set at deployment.
// Each trophy of the same tier is visually identical; metadata differentiates them.
//
// Four tiers carry a lifetime ceiling, enforced inside mint against a counter
// this contract keeps per tier name. Harvest is the only uncapped tier, and a
// tier name outside the five is refused, so no name reaches an uncounted slot.
// mint admits registry alone. CompetitionRegistry holds this contract in a
// one-shot reference and calls mint inside adjudicate, so the constants below
// are the only tier ceilings on this chain: the registry declares no tier
// constant and keeps no tier counter.
//
// This contract holds no owner. setTierSvg writes a tier's art, and the write
// splits in two: the deployer may fill a tier that holds none, which is what
// makes a deployment mintable, and every later write to a tier that already
// holds art admits governance alone, at INTERFACE. setGovernance is the one
// other wiring call, admitted once from the deployer.
// =============================================================================
pragma solidity 0.8.36;

import {ERC721} from "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import {Strings} from "@openzeppelin/contracts/utils/Strings.sol";
import {Base64} from "@openzeppelin/contracts/utils/Base64.sol";
import {IGovernedTrophy} from "./Governance.sol";
import {MetadataLib} from "./MetadataLib.sol";

contract AcervatorTrophy is ERC721, IGovernedTrophy {
    using Strings for uint256;

    // ── State ─────────────────────────────────────────────────────────────────

    uint256 private _nextTokenId = 1;

    /// The address that deployed this contract. It fills an empty tier once.
    address public immutable DEPLOYER;

    /// The Governance contract. Zero until setGovernance writes it, once.
    address public governance;

    /// Only CompetitionRegistry may mint trophies.
    address public immutable registry;

    // ── Tier lifetime supply caps (enforced in mint, immutable) ───────────────
    // Harvest has no constant and no ceiling. These four match the max_ever
    // values in src/competition/season_schedule.py RARITY_TIERS.

    uint256 public constant MAX_GOLD_FOLD         = 100_000;
    uint256 public constant MAX_BEAR_SLAYER       = 10_000;
    uint256 public constant MAX_GRAND_ACCUMULATOR = 1_000;
    uint256 public constant MAX_EKTHELIUS         = 21;

    mapping(string => uint256) public tierMinted;

    // ── Trophy metadata per token ─────────────────────────────────────────────

    struct TrophyMetadata {
        string  tier;            // "Harvest" | "Gold Fold" | "Bear Slayer" | ...
        string  tierEmoji;       // "🌾" | "🪙" | "🐻" | "⚡" | "∞"
        uint256 season;
        string  competitionId;
        uint256 rank;
        uint256 fieldSize;
        int256  advantageBps;    // e.g. 2950 = +29.50%
        string  marketRegime;    // "BULL" | "BEAR" | "SIDEWAYS" | "ANY"
        bytes32 merkleRoot;      // winning trade log commitment
        address botWallet;
        uint256 mintedAt;
    }

    mapping(uint256 => TrophyMetadata) public trophyData;

    // ── Tier SVG art (base64-encoded, set at deployment) ──────────────────────
    // Each value is the base64-encoded SVG for that tier.
    // Generated by trophy_generator.py and injected at deploy time.

    mapping(string => string) private _tierSvgB64;

    // ── Tier colors (for on-chain metadata) ───────────────────────────────────

    mapping(string => string) private _tierColor;

    // ── Tier emoji (for on-chain metadata) ────────────────────────────────────
    // One emoji per tier, so no caller can pair a tier with another tier's mark.
    // These five match the emoji field in src/competition/season_schedule.py
    // RARITY_TIERS.

    mapping(string => string) private _tierEmoji;

    // ── Events ────────────────────────────────────────────────────────────────

    event TrophyMinted(
        uint256 indexed tokenId,
        address indexed recipient,
        string  tier,
        uint256 season,
        string  competitionId,
        int256  advantageBps
    );

    event SvgUpdated(string tier);

    event GovernanceSet(address indexed governance);

    // ── Constructor ───────────────────────────────────────────────────────────

    constructor(address _registry) ERC721("Acervator Trophy", "ACTROPH") {
        require(_registry != address(0), "Trophy: registry cannot be zero");
        require(_registry.code.length > 0, "Trophy: registry not a contract");
        registry = _registry;
        DEPLOYER = msg.sender;

        // Tier colors (hex, for JSON attributes)
        _tierColor["Harvest"]           = "#FFCC44";
        _tierColor["Gold Fold"]         = "#FFD700";
        _tierColor["Bear Slayer"]       = "#FF3344";
        _tierColor["Grand Accumulator"] = "#00FFEE";
        _tierColor["Ekthelius"]         = "#FF00AA";

        _tierEmoji["Harvest"]           = unicode"🌾";
        _tierEmoji["Gold Fold"]         = unicode"🪙";
        _tierEmoji["Bear Slayer"]       = unicode"🐻";
        _tierEmoji["Grand Accumulator"] = unicode"⚡";
        _tierEmoji["Ekthelius"]         = unicode"∞";
    }

    // ── Modifiers ─────────────────────────────────────────────────────────────

    modifier onlyRegistry() {
        require(msg.sender == registry, "Trophy: caller is not registry");
        _;
    }

    // ── Governance wiring, once ───────────────────────────────────────────────

    /**
     * @notice Name the Governance contract that rewrites a filled tier, permanently.
     * @dev    Callable once, by the deployer, on an address that already holds code.
     * @param governanceAddress The deployed Governance address
     */
    function setGovernance(address governanceAddress) external {
        require(msg.sender == DEPLOYER, "Trophy: caller is not the deployer");
        require(governance == address(0), "Trophy: governance already set");
        require(governanceAddress.code.length > 0, "Trophy: governance not a contract");
        governance = governanceAddress;
        emit GovernanceSet(governanceAddress);
    }

    // ── SVG management ────────────────────────────────────────────────────────

    /**
     * @notice Upload the base64-encoded SVG for a tier.
     * @dev    The deployer fills a tier that holds no art, which is what makes a
     *         deployment mintable. Rewriting a tier that already holds art is a
     *         change to what every holder of that tier sees, so it admits
     *         governance alone. Each SVG is ~10-15KB base64, paid once per write.
     * @param tier      The tier name, one of the five
     * @param svgBase64 The base64-encoded SVG
     */
    function setTierSvg(string calldata tier, string calldata svgBase64) external override {
        if (bytes(_tierSvgB64[tier]).length == 0) {
            require(msg.sender == DEPLOYER, "Trophy: empty tier is the deployer's");
        } else {
            require(governance != address(0), "Trophy: governance not set");
            require(msg.sender == governance, "Trophy: filled tier is governance's");
        }
        _tierSvgB64[tier] = svgBase64;
        emit SvgUpdated(tier);
    }

    function getTierSvg(string calldata tier)
        external view returns (string memory)
    {
        return _tierSvgB64[tier];
    }

    // ── Minting ───────────────────────────────────────────────────────────────

    /**
     * @notice Mint a trophy NFT to the winning bot's wallet.
     * @dev    Called by CompetitionRegistry immediately after token award.
     *
     *         _safeMint is the last statement. The tier count, the metadata and
     *         the event all land first, so a recipient re-entering through
     *         onERC721Received reads a finished token.
     */
    function mint(
        address         recipient,
        string calldata tier,
        uint256         season,
        string calldata competitionId,
        uint256         rank,
        uint256         fieldSize,
        int256          advantageBps,
        string calldata marketRegime,
        bytes32         merkleRoot
    ) external onlyRegistry returns (uint256 tokenId) {
        require(recipient != address(0), "Trophy: mint to zero address");
        require(bytes(tier).length > 0,  "Trophy: empty tier");
        require(bytes(_tierSvgB64[tier]).length > 0,
                "Trophy: SVG not uploaded for this tier");

        _countTierMint(tier);

        tokenId = _nextTokenId++;

        trophyData[tokenId] = TrophyMetadata({
            tier:          tier,
            tierEmoji:     _tierEmoji[tier],
            season:        season,
            competitionId: competitionId,
            rank:          rank,
            fieldSize:     fieldSize,
            advantageBps:  advantageBps,
            marketRegime:  marketRegime,
            merkleRoot:    merkleRoot,
            botWallet:     recipient,
            mintedAt:      block.timestamp
        });

        emit TrophyMinted(tokenId, recipient, tier, season,
                          competitionId, advantageBps);

        _safeMint(recipient, tokenId);
    }

    // ── tokenURI — fully on-chain ─────────────────────────────────────────────

    /**
     * @notice Returns the full ERC-721 metadata as a base64-encoded data URI.
     *         No external URLs. Art and metadata fully on-chain.
     */
    function tokenURI(uint256 tokenId)
        public view override returns (string memory)
    {
        _requireOwned(tokenId);
        TrophyMetadata memory m = trophyData[tokenId];
        string memory svgB64   = _tierSvgB64[m.tier];

        // Build the JSON attributes array
        string memory attrs = string.concat(
            "[",
            MetadataLib.attr("Tier",           m.tier),          ",",
            MetadataLib.attr("Emoji",          m.tierEmoji),      ",",
            MetadataLib.attrNum("Season",      m.season),         ",",
            MetadataLib.attr("Competition",    m.competitionId),  ",",
            MetadataLib.attrNum("Rank",        m.rank),           ",",
            MetadataLib.attrNum("Field Size",  m.fieldSize),      ",",
            MetadataLib.attrSigned("Advantage (bps)", m.advantageBps), ",",
            MetadataLib.attr("Market Regime",  m.marketRegime),   ",",
            MetadataLib.attr("Tier Color",     _tierColor[m.tier]),
            "]"
        );

        // Advantage in human-readable form (e.g. "+29.50%")
        string memory advStr = MetadataLib.formatBps(m.advantageBps);

        string memory json = string.concat(
            "{\"name\":\"",
            m.tierEmoji, unicode" Acervator Trophy — ", m.tier,
            " #", tokenId.toString(),
            "\",\"description\":\"",
            "A Proof-of-Accumulation trophy awarded to the bot ranked #",
            m.rank.toString(),
            " in Competition ", m.competitionId,
            " (Season ", m.season.toString(), "). ",
            "Advantage: ", advStr, ". ",
            "Market: ", m.marketRegime, ". ",
            "Merkle root: 0x", MetadataLib.bytes32ToHex(m.merkleRoot),
            "\",\"image\":\"data:image/svg+xml;base64,", svgB64,
            "\",\"attributes\":", attrs,
            "}"
        );

        return string.concat(
            "data:application/json;base64,",
            Base64.encode(bytes(json))
        );
    }

    // ── Views ─────────────────────────────────────────────────────────────────

    function totalMinted() external view returns (uint256) {
        return _nextTokenId - 1;
    }

    function tokensOfOwner(address owner_, uint256 maxResults)
        external view returns (uint256[] memory)
    {
        uint256 total  = _nextTokenId - 1;
        uint256 count  = 0;
        uint256[] memory tmp = new uint256[](maxResults);
        for (uint256 i = 1; i <= total && count < maxResults; i++) {
            if (_ownerOf(i) == owner_) {
                tmp[count++] = i;
            }
        }
        uint256[] memory result = new uint256[](count);
        for (uint256 j = 0; j < count; j++) result[j] = tmp[j];
        return result;
    }

    function getTrophyTier(uint256 tokenId) external view returns (string memory) {
        return trophyData[tokenId].tier;
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /// @dev Refuses a tier outside the five and a mint at a capped tier's
    ///      ceiling, then raises that tier's counter.
    function _countTierMint(string calldata tier) private {
        bytes32 tierHash = keccak256(bytes(tier));
        if (tierHash == keccak256("Ekthelius")) {
            require(tierMinted[tier] < MAX_EKTHELIUS,
                    "Trophy: Ekthelius supply of 21 exhausted");
        } else if (tierHash == keccak256("Grand Accumulator")) {
            require(tierMinted[tier] < MAX_GRAND_ACCUMULATOR,
                    "Trophy: Grand Accumulator supply of 1,000 exhausted");
        } else if (tierHash == keccak256("Bear Slayer")) {
            require(tierMinted[tier] < MAX_BEAR_SLAYER,
                    "Trophy: Bear Slayer supply of 10,000 exhausted");
        } else if (tierHash == keccak256("Gold Fold")) {
            require(tierMinted[tier] < MAX_GOLD_FOLD,
                    "Trophy: Gold Fold supply of 100,000 exhausted");
        } else {
            require(tierHash == keccak256("Harvest"), "Trophy: unknown tier");
        }
        ++tierMinted[tier];
    }
}
